// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi55qY2pH03kMUu_HtuaRi-GCI_cvgCyQ',
    appId: '1:217370988969:web:e81d38567723ac2f8c74b8',
    messagingSenderId: '217370988969',
    projectId: 'bunny-note',
    authDomain: 'bunny-note.firebaseapp.com',
    storageBucket: 'bunny-note.firebasestorage.app',
    measurementId: 'G-MWNKNVYSV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl2RtkHNhayW3gauy6IX6Ogt8Lm7VssN4',
    appId: '1:217370988969:android:ab08fd9a92889fbb8c74b8',
    messagingSenderId: '217370988969',
    projectId: 'bunny-note',
    storageBucket: 'bunny-note.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLgQhDhrTWFo9QpWnTnoYBeWTmRp3LaQ',
    appId: '1:217370988969:ios:96c32d754136a4198c74b8',
    messagingSenderId: '217370988969',
    projectId: 'bunny-note',
    storageBucket: 'bunny-note.firebasestorage.app',
    iosBundleId: 'com.example.bunnynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcLgQhDhrTWFo9QpWnTnoYBeWTmRp3LaQ',
    appId: '1:217370988969:ios:96c32d754136a4198c74b8',
    messagingSenderId: '217370988969',
    projectId: 'bunny-note',
    storageBucket: 'bunny-note.firebasestorage.app',
    iosBundleId: 'com.example.bunnynote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi55qY2pH03kMUu_HtuaRi-GCI_cvgCyQ',
    appId: '1:217370988969:web:b742857b585f30888c74b8',
    messagingSenderId: '217370988969',
    projectId: 'bunny-note',
    authDomain: 'bunny-note.firebaseapp.com',
    storageBucket: 'bunny-note.firebasestorage.app',
    measurementId: 'G-RJXHYQGB08',
  );

}